### ISSUE TITLE
Setup environment

### ISSUE THREAD

**Issue by storkandstars** [SimplioOfficial/sio_core#1]
## Overview

Create a standalone dart library with [wallet-core](https://github.com/trustwallet/wallet-core/tree/master/src) lib implementation.

### Outcome

Decoupled `blockchain` implementation for our flutter app

### Requirements

- [Semantic versioning](https://semver.org/) of this library `major.minor.patch`
- automatic unit and interrogation tests
- automatic deployment and versioning

### Task list
- [ ] #2 
- [x] #6 
- [x] #4
- [x] #5

**Comment by ciripel** [comment]
Testing now release 0.0.3 -> publish to pub.dev cd

**Comment by ciripel** [comment]
Automatic pushing to pub.dev successfully implemented!

**Comment by ciripel** [comment]
Reopened due to #4 reopening
