### ISSUE TITLE
Update sio_core with new BE methods for Bitcoin network

### ISSUE THREAD

**Issue by daxicek** [SimplioOfficial/sio_core#67]
# Overview

There is a new way of handeling calls between chains, explorers and client. Regarding these new changes we need to update our library with new type of communication.

## Outcome

sio_core library will be updated with proper ID of asset for Bitcoin and proper calls to backend

## Requirements

- Get proper ID of Bitcoin with /assets/system-assets endpoint
- Change Tx Broadcast endpoint
- Change Get Balance endpoint
- Change Get Tx History endpoint
- Change Get Utils endpoint

**Comment by ciripel** [comment]
This will be done directly in simplio-app.
