### ISSUE TITLE
Update sio_core library with new fee endpoints

### ISSUE THREAD

**Issue by daxicek** [SimplioOfficial/sio_core#68]
# Overview

There is a new way of handeling calls between chains, explorers and client. Regarding these new changes we need to update our library with new type of communication.

## Outcome

sio_core library will be using new endpoints for getting fees from Bitcoin, Binance Smart Chain and Solana

## Requirements

- Get proper ID of asset with /assets/system-assets endpoint
- Change Fee endpoints in sio_core

**Comment by ciripel** [comment]
This will be done in simplio-app directly.
